on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10,22 * * 1-5'

name: Auto-Write Current Time

jobs:
  auto-add:
    runs-on: ubuntu-latest
    env:
      MY_GITHUB_REPO: ${{ github.repository }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TOKENCODR_DEMO_PASSWORD: ${{ secrets.TOKENCODR_DEMO_PASSWORD }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Setup R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache-version: 1

      - name: Write Current Time
        run: |
          Rscript -e 'source("scripts/write-data.R")'


